parent_cfg: configs/waymo_val_121.yaml
source_path: ./data/waymo/049
exp_name: waymo_val_049

data:
    selected_frames: [93, 193]

diffusion:
    use_img_diffusion: False

diffusion:
    use_diffusion: False